# Generated by Django 5.0.1 on 2024-02-12 01:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pdfdocument",
            name="uploaded_at",
        ),
        migrations.AddField(
            model_name="pdfdocument",
            name="pdf_text",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="pdfdocument",
            name="pdf_file",
            field=models.FileField(upload_to="pdf_files/"),
        ),
    ]
