# Generated by Django 5.0.1 on 2024-02-12 03:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "questions",
            "0002_remove_pdfdocument_uploaded_at_pdfdocument_pdf_text_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="pdfdocument",
            name="uploaded_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="pdfdocument",
            name="pdf_text",
            field=models.TextField(blank=True),
        ),
    ]
