# Generated by Django 5.0.1 on 2024-02-12 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0003_pdfdocument_uploaded_at_alter_pdfdocument_pdf_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pdfdocument",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
