# Generated by Django 5.0.1 on 2024-02-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0004_alter_pdfdocument_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("context", models.TextField()),
                ("question", models.CharField(max_length=355)),
                ("answer", models.CharField(blank=True, max_length=2000)),
            ],
        ),
    ]
